project:
  type: website
  output-dir: _site

website:
  title: "Lemming ponsel DO and Temperature"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Lemming_Ponsel_Optode.qmd
        text: Data

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
    embed-resources: true
    css: styles.css
