name: Render and Publish Quarto Site

on:
  schedule:
    #- cron: '0 * * * *'  # every hour minute 0 UTC
    #- cron: '30 * * * *'  # At minute 30 past every hour - uncomment this if needed
  workflow_dispatch:     # Allows manual triggering

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y \
         libcurl4-openssl-dev \
         libssl-dev \
         libxml2-dev \
         libharfbuzz-dev \
         libfribidi-dev \
         libfreetype6-dev \
         libpng-dev \
         libtiff5-dev \
         libjpeg-dev \
         zlib1g-dev \
         libfontconfig1-dev     # <-- this fixes the fontconfig error

      - name: Install R packages
        run: Rscript install-packages.R

      - name: List installed packages
        run: Rscript -e 'installed.packages()[,1]'

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
